1 entities setup
D17-Le-groupe-3/back-end pull request #16
Opened 2022-02-16 14:56 UTC by lpousse

2022-02-16 15:10 UTC, kevinWAC approved these changes, later dismissed

2022-02-16 16:13 UTC, kevinWAC approved these changes, later dismissed

2022-02-18 10:19 UTC, Andrufus requested changes

2022-02-18 10:19 UTC, Andrufus commented on src/main/java/fr/diginamic/digiday/entities/Service.java
> +
Est-ce qu'on rajouterait pas la relation avec User ici ?

2022-02-18 10:19 UTC, Andrufus commented on src/main/java/fr/diginamic/digiday/enums/LeaveStatus.java
> +}
C'est pas en anglais tout ça 😉

2022-02-18 10:40 UTC, Andrufus requested changes

2022-02-18 10:40 UTC, Andrufus commented on src/main/java/fr/diginamic/digiday/entities/Company.java
> +	private List<Department> department;
Manque le S (pareil pour getter/setter)

2022-02-18 10:42 UTC, Andrufus approved these changes
👍

2022-02-18 10:43 UTC, kevinWAC approved these changes

2022-02-18 10:45 UTC, merged