7 leave delete
D17-Le-groupe-3/back-end pull request #22
Opened 2022-02-22 13:14 UTC by lodev44

Bach Delete features

2022-02-22 13:38 UTC, Andrufus requested changes

2022-02-22 13:38 UTC, Andrufus commented on src/main/java/fr/diginamic/digiday/controller/LeaveController.java
> +    }
On dirait qu'il y a un soucis d'indentation par ici

2022-02-22 16:33 UTC, Andrufus submitted a review, later dismissed

2022-02-23 10:05 UTC, lpousse approved these changes

2022-02-23 10:14 UTC, kevinWAC approved these changes

2022-02-23 10:15 UTC, merged